Add files via upload
yoshida-prog/b-teck_practice4 pull request #1
Opened 2021-01-10 21:09 UTC by yoshida-prog

API・非同期通信を用いてクイズゲームを作成

2021-01-11 13:12 UTC, myzktkyk requested changes
動作は問題ありませんでした。
コードについて何点か指摘があります。

2021-01-11 13:12 UTC, myzktkyk commented on main.js
> +      const QUIZ_DATA = data.results;
ここだけ大文字なのが気になりました。

2021-01-11 13:12 UTC, myzktkyk commented on main.js
> +startBtn.addEventListener('click', () => {
`startBtn` という変数がどこにも宣言されていないようです。

2021-01-11 14:41 UTC, yoshida-prog commented on main.js
> +startBtn.addEventListener('click', () => {
開始ボタンのbuttonタグにid="startBtn"としていました！
main.jsの最初の方にSTART_BUTTON で開始ボタンのDOMを定義していましたが使っていませんでした。
なんでエラーにならないのか？と思い、42行目のクリックイベント直下にconsole.log(startBtn);を行うと、開始ボタンのDOMを持ってきました！
書き方としては見ないですがこういった動きもできるんですね！
<img width="737" alt="スクリーンショット 2021-01-11 23 35 44" src="https://user-images.githubusercontent.com/56685063/104195887-833ad380-5466-11eb-8016-9f5b38943f51.png">

2021-01-11 14:50 UTC, yoshida-prog commented
指摘箇所を修正しました。

2021-01-12 10:01 UTC, myzktkyk commented on main.js
> +startBtn.addEventListener('click', () => {
>書き方としては見ないですがこういった動きもできるんですね！

javascript は良くも悪くも厳密さがない言語です（最近は厳密さが増してきましたが）
厳密さがないことは「よくわかってなくてもなんとなく動く」というメリットがある反面
「いざ問題が起こった時に、原因が掴みにくくなる」と言うデメリットを抱えることになります。
昨今では「デメリットの方がきつい」という風潮になってきたので
厳密であることが求められる場面が増えてます。

2021-01-12 10:07 UTC, myzktkyk requested changes
何点か気にになる点があったので指摘をしております 🙇

2021-01-12 10:07 UTC, myzktkyk commented on main.js
> +const START_BUTTON = document.getElementById('startBtn');
大文字のスネークケース(`_` で連結する)にする場合は定 `数` の時だけかと思います。
`API_URL` は定 `数` なのでいいのですが、これ以降は定数ではないので、以下のように書いた方がいいと思います。
https://qiita.com/satotaka/items/21da1ccc0171df85d053

```suggestion
const startButton = document.getElementById('startBtn');
```

2021-01-12 10:07 UTC, myzktkyk commented on main.js
> +            let ANSWERS_LENGTH = answersData.length;
```suggestion
            let answersLength = answersData.length;
```

2021-01-12 10:07 UTC, myzktkyk commented on main.js
> +            const RESTART = document.getElementById('restartBtn');
```suggestion
            const restart = document.getElementById('restartBtn');
```

2021-01-12 11:42 UTC, yoshida-prog commented
変数名を変更しました。

2021-01-13 05:08 UTC, merged